seed: 43

vocab_size: 41

train_dataloader:
  type: 'AudioDatasetLoader'
  params:
    root_dir: '/app/datasets/audio_dataset/'
    batch_size: 3
    spec_shape: [1024, 1024]

model:
  type: 'DeepSpeech2'
  params:
    input_dim: 1024 # spec_shape[1]
    output_dim: 41 # vocab_size
    rnn_layers: 5
    rnn_units: 512

optimizer:
  type: Adam
  params:
    learning_rate: 0.001

loss:
  type: CTCLoss

scheduler:
  type: WarmupCosineScheduler
  params:
    num_warmup_steps: 10
    lr_max: 1e-3
    num_training_steps: 10,
    warmup_method: 'log'
    num_cycles: 0.5

metrics:
  - type: WordErrorRate
    params:
      decoder:
        type: CTCDecoder

callbacks:
  ...

train:
  precision: 'fp32'
  epochs: 50
